name: Deploy Static Website to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy static site to EC2
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i private_key" ./html/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html --exclude '.git'
